server:
  port: 80
spring:
  application: 
    name: LuckDrawPay
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/alipay_apy?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20                       #最大线程数
    dbcp2:                                        #  进行数据库连接池的配置
      min-idle: 5                                 #  数据库连接池的最小维持连接数
      initial-size: 5                             #  初始化提供的连接数
      max-total: 5                                #  最大连接数
      max-wait-millis: 200   
  redis: 
    database: 15
    host: 127.0.0.1 
    port: 6379  
    password: 123456 
    timeout: 1000                                #连接超时时间（毫秒）  
    jedis: 
      pool: 
        max-active: 200                            #连接池最大连接数（使用负值表示没有限制）  
        max-wait: -1                               # 连接池最大阻塞等待时间（使用负值表示没有限制）  
        max-idle: 10                               # 连接池中的最大空闲连接  
        min-idle: 0                                # 连接池中的最小空闲连接  
eureka: 
  client:
    serviceUrl: 
      defaultZone: http://127.0.0.1:9100/eureka/
mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml    #  mybatis主配置文件所在路径
  mapper-locations:  classpath:mybatis/mapper/*.xml     #  所有的mapper映射文件
tx-lcn: 
  client: 
    manager-address: 127.0.0.1:9999

    
    